contact_links:
  - name: IRC
    url: http://example.com
    about: Chat
  - name: Slack
    url: http://example.com/slack
    about: Chat elsewhere
  - name: Nope
    url: bogus
    about: Not gonna show up
