blank_issues_enabled: true
contact_links:
  - name: hello
    about: hi hi hi hi hi hi hi hi hi hi hi hi 
    url: http://hello.com<script>
  - name: hi hi
    about: hi hi hi hi hi hi hi hi hi hi hi hi
    url: http://hello.com
  - name: heya
    about: hi hi hi hi hi hi hi hi hi hi hi hi
    url: http://hello.com
  - name: hey
    about: hi hi hi hi hi hi hi hi hi hi hi hi
    url: http://hello.com
